name: ChrisH
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3612321144901216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6291499075014144
  lightness: 0.28698558476753533
  saturation: 0
  rhythmicContrast: 0.3168205835390836
purpose: []
